config/routes.rb
Spree::Core::Engine.add_routes do
  post 'add_item_to_cart/', to: 'add_items#create', as: 'quick_add'
  get 'parts-and-accessories', to: 'add_items#index'
  resources :add_items, only: [:index, :create]
end

app/models/spree/part.rb
class Spree::Part < ActiveRecord::Base
end

app/controllers/spree/add_items_controller.rb
module Spree
  class AddItemsController < Spree::StoreController
    include Spree::ProductsHelper
    include Spree::FrontendHelper
    before_action :load_taxon

    def create
      find_variant = params[:variant]
      variant = Spree::Variant.find(find_variant)
      unless current_order.present?
        Spree::Order.create
      end
      Spree::Cart::AddItem.call(order: current_order, variant: variant,  quantity: 1)
      redirect_to '/parts-and-accessories'
      flash[:success] = "Added #{ variant.name } to your cart"
    end

    def index
      @categories = Spree::Taxon.find_by(name: 'Parts & Accessories')
    end

    private

    def load_taxon
      @taxon = Spree::Taxon.friendly.find_by(permalink: 'parts-and-accessories')
    end
  end
end

app/controllers/spree/add_to_cart_controller.rb
module Spree
  class AddToCartController < StoreController
    skip_before_action :verify_authenticity_token, only: [:create]
    include Spree::ProductsHelper
    include Spree::FrontendHelper

    def index
    end

    def create
      variant = Spree::Variant.find(params[:variant])

      @product = variant
      Spree::Cart::AddItem.call(order: current_order, variant: variant, quantity: 1)
      flash[:success] = "#{ variant.name } Add to Cart"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/views/spree/add_items/_add_item_to_cart.haml
- variant = Spree::Variant.find(variant_id)
%table.table.striped
  %tr
  = form_tag quick_add_path, method: :post do
    = hidden_field_tag :variant, variant_id
    %td
      = variant.name
    %td.price{width: "25%"}
      %strong
        = "$#{variant.price}"
    %td{width: "25%"}
      -# = submit_tag
      -# %button#add-to-cart-button.btn.btn-primary.w-100.text-uppercase.font-weight-bold.add-to-cart-button{:name => "button", :type => "submit"}
        Add To Cart

app/views/spree/add_items/index.haml
- current_page_name = 'Parts and Accessories'
#page_content.mt-4.mb-4
  .container
    .row
      %nav#breadcrumbs.col-12.mt-1.mt-sm-3.mt-lg-4
        %ol.breadcrumb
          %li.breadcrumb-item
            %span
              = link_to Spree.t('plp.home'), spree.root_path
            %li.breadcrumb-item
              = current_page_name
.container
  - @categories.children.each do |children|
    .row
      .col-sm-12
        %h2
          = children.name
          -# = render partial: 'add_item_to_cart', locals: { variant_id: product.variants.first.id, name: product.name, price: product.variants.first }
        - children.products.each do |product|
          - variant_id = Spree::Variant.find(product.variants.first.id)
          - variant = Spree::Variant.find(variant_id.id)
          %table.table.striped
            %tr
            = form_tag quick_add_path, method: :post do
              = hidden_field_tag :variant, variant.id
              %td
                = variant.name
              %td.price{width: "25%"}
                %strong
                  = "$#{variant.price}"
              %td{width: "25%"}
                = submit_tag
                -# %button#add-to-cart-button.btn.btn-primary.w-100.text-uppercase.font-weight-bold.add-to-cart-button{:name => "button", :type => "submit"}
                  Add To Cart

app/views/spree/shared/_add_item_to_cart.haml
- variant = Spree::Variant.find(variant_id)
%table.table.striped
  %tr
  = form_tag quick_add_path, method: :post do
    = hidden_field_tag :variant, variant_id
    %td
      = variant.name
    %td.price{width: "25%"}
      %strong
        = "$#{variant.price}"
    %td{width: "25%"}
      %button#add-to-cart-button.btn.btn-primary.w-100.text-uppercase.font-weight-bold.add-to-cart-button{:name => "button", :type => "submit"}
        Add To Cart